### ISSUE TITLE
Check out http://avatars.io/

### ISSUE THREAD

**Issue by nschloe** [paperhub/paperhub-frontend#54]
Do they have SVG, image caching?

**Comment by andrenarchy** [comment]
What do you mean with "image caching"?

**Comment by nschloe** [comment]
![cache](https://cloud.githubusercontent.com/assets/181628/6438359/9258f9ce-c0c8-11e4-8e0b-361088a01161.png)

**Comment by andrenarchy** [comment]
Ah, thx! :) Gravatar sets the `Expires` header to 5 minutes. This seems to be reasonable: it only takes 5 minutes to see an updated picture. If it's raised – let's say to 1 week – you may confuse or frustrate users because they don't see updated pictures. The traffic generated by Gravatar requests is negligible compared to other requests we have (e.g., PDFs or PDF chunks).

Anyway, I wouldn't take the google tool too seriously – it always recommends aggressive caching because it doesn't know which content may change.

**Comment by nschloe** [comment]
>  Gravatar sets the Expires header to 5 minutes.

`expire` and `cache-control` are fine, I suppose what's missing is `etag`. Anyhow it's the only cache-relevant header that I see Gravatar doesn't set.

**Comment by nschloe** [comment]
Avatars.io only redirects to gravatar and doesn't set and additional tags. Byes.
